package ba.unsa.etf.rpr.business;


import ba.unsa.etf.rpr.dao.DaoFactory;
import ba.unsa.etf.rpr.domain.IssuedBook;
import ba.unsa.etf.rpr.domain.User;
import ba.unsa.etf.rpr.exceptions.LibraryException;

import java.util.List;

/***
 * Business logic of IssuedBook bean
 */
public class IssuedBooksManager {

    /***
     * Issues another book
     * @param issuedBook
     * @return
     * @throws LibraryException
     */
    public IssuedBook add(IssuedBook issuedBook) throws LibraryException {
        if(issuedBook.getId()!=0){
            throw new LibraryException("Can't issue a book with issueID. ID is autogenerated");
        }



        try {
            return DaoFactory.issuedBooksDao().add(issuedBook);
        }catch(LibraryException e){
            throw e;
        }
    }

    /***
     * Deletes an issue. Basically, it is called whenever user returns book to library
     * @param issuedBookId
     */
    public void delete(int issuedBookId){
        DaoFactory.issuedBooksDao().delete(issuedBookId);
    }

    /***
     * This method gets all issues from database
     * @return
     */
    public List<IssuedBook> getAll(){
        return DaoFactory.issuedBooksDao().getAll();
    }
}
